version: '3.8'

services:
  # FastAPI Backend Service
  api:
    build: .
    container_name: ad-insights-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    command: ["python", "src/api.py"]
    networks:
      - ad-insights-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Streamlit Dashboard Service
  dashboard:
    build: .
    container_name: ad-insights-dashboard
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - API_BASE_URL=http://api:8000
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    command: [
      "streamlit", "run", "src/dashboard.py",
      "--server.port=8501",
      "--server.address=0.0.0.0",
      "--server.headless=true",
      "--server.enableCORS=false",
      "--server.enableXsrfProtection=false"
    ]
    depends_on:
      - api
    networks:
      - ad-insights-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ad-insights-network:
    driver: bridge

volumes:
  ad-insights-data:
    driver: local
